import avatar from "../../assets/images/navbar/profile.png"

export const dummyDataForDataTable = [
   {
      responsive_id: "",
      id: 1,
      contact: "7854785478",
      user_id: "132",
      sign_up_via: "email",
      avatar: avatar,
      full_name: "Korrie O'Crevy",
      post: "Nuclear Power Engineer",
      role: 1,
      team_status: 1,
      email: "kocrevy0@thetimes.co.uk",
      country: "Krasnosilka",
      start_date: "09/23/2016",
      status: 2,
      payment_ETA_status: "mar-2023"
   },
   {
      responsive_id: "",
      id: 2,
      avatar: avatar,
      contact: "7854785478",
      user_id: "132",
      sign_up_via: "facebook",
      full_name: "Bailie Coulman",
      post: "VP Quality Control",
      role: 2,
      team_status: 2,
      email: "bcoulman1@yolasite.com",
      country: "Hinigaran",
      start_date: "05/20/2018",
      status: 2,
      payment_ETA_status: "apr-2023"
   },
   {
      responsive_id: "",
      id: 3,
      avatar: avatar,
      contact: "7854785478",
      user_id: "132",
      sign_up_via: "apple",
      full_name: "Stella Ganderton",
      post: "Operator",
      role: 1,
      team_status: 1,
      email: "sganderton2@tuttocitta.it",
      country: "Golcowa",
      start_date: "03/24/2018",
      status: 3,
      payment_ETA_status: "oct-2023"
   },
   {
      responsive_id: "",
      id: 4,
      avatar: avatar,
      contact: "7854785478",
      user_id: "132",
      sign_up_via: "google",
      full_name: "Dorolice Crossman",
      post: "Cost Accountant",
      role: 3,
      team_status: 1,
      email: "dcrossman3@google.co.jp",
      country: "Paquera",
      start_date: "12/03/2017",
      status: 1,
      payment_ETA_status: "jan-2023"
   },
   {
      responsive_id: "",
      id: 5,
      avatar: avatar,
      contact: "7854785478",
      user_id: "132",
      sign_up_via: "facebook",
      full_name: "Harmonia Nisius",
      post: "Senior Cost Accountant",
      role: 1,
      team_status: 1,
      email: "hnisius4@gnu.org",
      country: "Lucan",
      start_date: "08/25/2017",
      status: 2,
      payment_ETA_status: "aug-2023"
   },
   {
      responsive_id: "",
      id: 6,
      avatar: avatar,
      contact: "7854785478",
      user_id: "132",
      sign_up_via: "email",
      full_name: "Genevra Honeywood",
      post: "Geologist",
      role: 1,
      team_status: 1,
      email: "ghoneywood5@narod.ru",
      country: "Maofan",
      start_date: "06/01/2017",
      status: 1,
      payment_ETA_status: "sep-2023"
   },
   {
      responsive_id: "",
      id: 7,
      avatar: avatar,
      contact: "7854785478",
      user_id: "132",
      sign_up_via: "google",
      full_name: "Eileen Diehn",
      post: "Environmental Specialist",
      role: 4,
      team_status: 2,
      email: "ediehn6@163.com",
      country: "Lampuyang",
      start_date: "10/15/2017",
      status: 3,
      payment_ETA_status: "oct-2023"
   },
   {
      responsive_id: "",
      id: 8,
      avatar: avatar,
      contact: "7854785478",
      user_id: "132",
      sign_up_via: "apple",
      full_name: "Richardo Aldren",
      post: "Senior Sales Associate",
      role: 1,
      team_status: 1,
      email: "raldren7@mtv.com",
      country: "Skoghall",
      start_date: "11/05/2016",
      status: 3,
      payment_ETA_status: "mar-2023"
   },
   {
      responsive_id: "",
      id: 9,
      avatar: avatar,
      contact: "7854785478",
      user_id: "132",
      sign_up_via: "apple",
      full_name: "Allyson Moakler",
      post: "Safety Technician",
      role: 3,
      team_status: 1,
      email: "amoakler8@shareasale.com",
      country: "Mogilany",
      start_date: "12/29/2018",
      status: 2,
      payment_ETA_status: "apr-2023"
   },
   {
      responsive_id: "",
      id: 10,
      avatar: avatar,
      contact: "7854785478",
      user_id: "132",
      sign_up_via: "google",
      full_name: "Merline Penhalewick",
      post: "Junior Executive",
      role: 1,
      team_status: 1,
      email: "mpenhalewick9@php.net",
      country: "Kanuma",
      start_date: "04/19/2019",
      status: 2,
      payment_ETA_status: "nov-2023"
   },
   {
      responsive_id: "",
      id: 11,
      avatar: avatar,
      contact: "7854785478",
      user_id: "132",
      sign_up_via: "facebook",
      full_name: "De Falloon",
      post: "Sales Representative",
      role: 1,
      team_status: 2,
      email: "dfalloona@ifeng.com",
      country: "Colima",
      start_date: "06/12/2018",
      status: 1,
      payment_ETA_status: "mar-2023"
   },
   {
      responsive_id: "",
      id: 12,
      avatar: avatar,
      contact: "7854785478",
      user_id: "132",
      sign_up_via: "facebook",
      full_name: "Cyrus Gornal",
      post: "Senior Sales Associate",
      role: 1,
      team_status: 1,
      email: "cgornalb@fda.gov",
      country: "Boro Utara",
      start_date: "12/09/2017",
      status: 2,
      payment_ETA_status: "jul-2023"
   },
   {
      responsive_id: "",
      id: 13,
      avatar: avatar,
      contact: "7854785478",
      user_id: "132",
      sign_up_via: "facebook",
      full_name: "Tallou Balf",
      post: "Staff Accountant",
      role: 3,
      team_status: 2,
      email: "tbalfc@sina.com.cn",
      country: "Siliana",
      start_date: "01/21/2016",
      status: 3,
      payment_ETA_status: "jan-2023"
   },
   {
      responsive_id: "",
      id: 14,
      avatar: avatar,
      contact: "7854785478",
      user_id: "132",
      sign_up_via: "facebook",
      full_name: "Othilia Extill",
      post: "Associate Professor",
      role: 1,
      team_status: 1,
      email: "oextilld@theatlantic.com",
      country: "Brzyska",
      start_date: "02/01/2016",
      status: 2,
      payment_ETA_status: "dec-2023"
   },
   {
      responsive_id: "",
      id: 15,
      avatar: avatar,
      contact: "7854785478",
      user_id: "132",
      sign_up_via: "facebook",
      full_name: "Wilmar Bourton",
      post: "Administrative Assistant",
      role: 4,
      team_status: 1,
      email: "wbourtone@sakura.ne.jp",
      country: "Bích Động",
      start_date: "04/25/2018",
      status: 3,
      payment_ETA_status: "mar-2023"
   },
   {
      responsive_id: "",
      id: 16,
      avatar: avatar,
      contact: "7854785478",
      user_id: "132",
      sign_up_via: "facebook",
      full_name: "Robinson Brazenor",
      post: "General Manager",
      role: 1,
      team_status: 1,
      email: "rbrazenorf@symantec.com",
      country: "Gendiwu",
      start_date: "12/23/2017",
      status: 1,
      payment_ETA_status: "feb-2023"
   },
   {
      responsive_id: "",
      id: 17,
      avatar: avatar,
      contact: "7854785478",
      user_id: "132",
      sign_up_via: "facebook",
      full_name: "Nadia Bettenson",
      post: "Environmental Tech",
      role: 1,
      team_status: 2,
      email: "nbettensong@joomla.org",
      country: "Chabařovice",
      start_date: "07/11/2018",
      status: 1,
      payment_ETA_status: "may-2023"
   },
   {
      responsive_id: "",
      id: 18,
      avatar: avatar,
      contact: "7854785478",
      user_id: "132",
      sign_up_via: "facebook",
      full_name: "Titus Hayne",
      post: "Web Designer",
      role: 1,
      team_status: 1,
      email: "thayneh@kickstarter.com",
      country: "Yangon",
      start_date: "05/25/2019",
      status: 1,
      payment_ETA_status: "aug-2023"
   },
   {
      responsive_id: "",
      id: 19,
      avatar: avatar,
      contact: "7854785478",
      user_id: "132",
      sign_up_via: "facebook",
      full_name: "Roxie Huck",
      post: "Administrative Assistant",
      role: 1,
      team_status: 1,
      email: "rhucki@ed.gov",
      country: "Polýkastro",
      start_date: "04/04/2019",
      status: 2,
      payment_ETA_status: "mar-2023"
   },
   {
      responsive_id: "",
      id: 20,
      avatar: avatar,
      contact: "7854785478",
      user_id: "132",
      sign_up_via: "facebook",
      full_name: "Latashia Lewtey",
      post: "Actuary",
      role: 1,
      team_status: 1,
      email: "llewteyj@sun.com",
      country: "Hougong",
      start_date: "08/03/2017",
      status: 1,
      payment_ETA_status: "jan-2023"
   }
]
